### ISSUE TITLE
Fix Footer Positioning

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/docs#12]
Rather than floating (where you can see the bug below from <https://apis.do>, I think the way to fix the footer is just to set the main content section to have a min height of something like `90vh`

<img width="1116" alt="Screen Shot 2022-09-28 at 1 51 24 AM" src="https://user-images.githubusercontent.com/4130910/192708845-92d61f31-b8c0-4f80-9a24-a6409281eca8.png">

**Comment by crisner1978** [comment]
Fixed the footer, no more floating.

**Comment by crisner1978** [comment]
Fixed a while ago. Forgot to update the ticket.
