### ISSUE TITLE
Get Started Button OAuth and UX

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/docs#14]
We probably want to keep the button going to oauth.do/login as the default, because we don't want to rely on a configuration that the /login route of the local domain is setup properly ... but we could add a query param to properly redirect back to the domain, and/or whatever the preferred action is ... like if it's templates.do or worker.templates.do where the action is to create a new repo at <https://github.com/drivly/worker.templates.do/generate> we would want to redirect there after logging in ... so maybe the correct/simplest login link is just <https://oauth.do/login?redirect=https://github.com/drivly/worker.templates.do/generate> because we don't actually need cookies stored on that domain, we'd just be trying to capture emails as appropriate and necessary

So @sam-lippert we need to figure out how to do this and then update the docs template with the appropriate link (preferably with the dynamic callback action like <https://github.com/drivly/worker.templates.do/generate> coming from a setting in `_config.yaml` so it can be easily created in the template with a default of /api

**Comment by sam-lippert** [comment]
Oauth.do now allows redirects to arbitrary urls, but if the url doesn't pass validation logic (source/destination hosts must match), the login cookie isn't passed.
We can shim in validation for a list of domains that allow the cookie to be passed anyways.

**Comment by crisner1978** [comment]
so for the I have in docs yaml the following which is then connected to the button
gettingStarted: "https://github.com/drivly/worker.templates.do/generate"

should I change it to this one  https://oauth.do/login?redirect=https://github.com/drivly/worker.templates.do/generate/  

or???

**Comment by sam-lippert** [comment]
@crisner1978 I tested out the login redirect on ctx.do, and it looks good to me.

**Comment by crisner1978** [comment]
@sam-lippert awesome!
