### ISSUE TITLE
Add Get Started button back in

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/docs#16]
we need to make this dynamic, so maybe a `gettingStarted` prop in the `_config.yaml` can let you override to do a different action, like maybe Use This Template <https://github.com/drivly/worker.templates.do/generate> ... but for the vast majority of these, we want to redirect the user to oauth.do/login and then have them redirect back to the original domain /api to see the API endpoint

@sam-lippert has #14 to figure out the redirects, but we need to put back the Get Started button in the meantime

**Comment by crisner1978** [comment]
added the Button back and created gettingStarted variable in the yaml for the href... and for the docs set it to the Template https://github.com/drivly/worker.templates.do/generate

**Comment by crisner1978** [comment]
this link is in the config.yaml gettingStarted: /login?redirect_uri=https://github.com/drivly/worker.templates.do/generate

going to a 404 page not found => https://github.com/login/callback?state=89479662-60d6-45cb-a7ca-43354aefbfbc
