### ISSUE TITLE
Add Link Preloading

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/docs#17]
Simplest to use is probably <https://instant.page> which is also running on cloudflare workers.

To implement, let's put this right before the closing `</body>`

```html
<script src="//instant.page/5.1.1" type="module" integrity="sha384-MWfCL6g1OTGsbSwfuMHc8+8J2u71/LA8dzlIN3ycajckxuZZmF+DNjdm7O6H3PSq"></script>
```
External links aren’t preloaded by default (and we want them to, so all the links across our domains will load instantly then), to allow them all add a `data-instant-allow-external-links` attribute to the `<body>`.

**Comment by crisner1978** [comment]
added the script and the attribute

**Comment by crisner1978** [comment]
Added a while ago. Complete
