### ISSUE TITLE
Fix very weird formatting

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/docs#18]
See <https://oauth.do>

<img width="1149" alt="Screen Shot 2022-09-30 at 7 05 25 AM" src="https://user-images.githubusercontent.com/4130910/193265903-716ff112-1d39-4806-8fab-e6d747009965.png">

**Comment by nathanclevenger** [comment]
Oh, I realize that this is also mermaid that's broken ... @sam-lippert had originally implemented mermaid working correctly in the template , but we need to make sure to get that resolved

**Comment by crisner1978** [comment]
yeah I didn't touch it but I did add the autoloader cdn for prismjs maybe that could be causing the issue

**Comment by crisner1978** [comment]
I commented out the Prismjs and the Mermaid magically works. I tried the plugin that Prism has for Mermaid and that didn't work. I tried loading the languages separately instead of using the prism language loader... still nope. I can't seem to get them working together. Any ideas?

**Comment by crisner1978** [comment]
Formatting was fixed a while ago. Complete
