### ISSUE TITLE
Footer & ending content seems off balance

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/docs#20]
The stars and Edit this page should go lower too ... and the actually footer is off the page ... I don't think this looks right if it's a short bit of content like this

<img width="1378" alt="Screen Shot 2022-09-30 at 7 24 36 AM" src="https://user-images.githubusercontent.com/4130910/193269030-0de76440-93f0-4035-95d6-5c2400d450bf.png">

**Comment by crisner1978** [comment]
Got it... adjusted so stars and edit will always stay near the bottom

**Comment by crisner1978** [comment]
It has been balanced a while back. Complete
