### ISSUE TITLE
Get PrismJS properly formatting code in Dracula

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/docs#3]

**Comment by nathanclevenger** [comment]
@bryant22 I didn't spend a ton of time, but I couldn't get this working ... I know you're overhauling the design right now, but getting prismjs is going to be key as code snippets are central to all of our doc pages ... so if you can't figure it out either, maybe we could see if @crisner1978 has any ideas

**Comment by crisner1978** [comment]
Prism seems to have a plugin for exactly this. You can download it here: http://prismjs.com/plugins/autolinker/. You can use this format:
[Text you want to see](http://url-goes-here.com)

**Comment by bryant22** [comment]
@Chris Risner - let's work on this after lunch 👍

**Comment by nathanclevenger** [comment]
@crisner1978 I see the issue with Prism - you're referencing a local .js file not from a CDN ... I just noticed this because I saw the logs of the APIs and we're getting requests in the API for \prism.js ... so switch that to a CDN and we should be good

```
    <script src="../prism.js"></script>
    <script src="https://unpkg.com/prismjs@v1.x/plugins/autoloader/prism-autoloader.min.js"></script>
```

**Comment by crisner1978** [comment]
Got it thanks... switched it to cdns

**Comment by nathanclevenger** [comment]
The default Dracula in prism isn't as good IMHO as the Pretty JSON plugin on Safari ...

<img width="644" alt="Screen Shot 2022-09-30 at 8 48 22 AM" src="https://user-images.githubusercontent.com/4130910/193284245-29941e4a-c4ff-46f6-9fa1-91e979e69203.png">

**Comment by crisner1978** [comment]
Prism.js properly formatting code.
